#!/usr/bin/env bash
# Run on ECS as the approved deploy account, never as root.
# Args: deploy-path release-id service-name live-port base-path candidate-port
set -Eeuo pipefail
root=${1:?deploy path}; release_id=${2:?release id}; service=${3:?service}; port=${4:?live port}; base=${5:?base}; candidate_port=${6:?candidate port}
[[ "$root" =~ ^/srv/[a-zA-Z0-9_-]+$ && "$release_id" =~ ^[0-9]+-[0-9a-f]{40}$ && "$service" =~ ^[a-zA-Z0-9_-]+$ ]] || { echo 'Invalid release parameters' >&2; exit 1; }
[[ "$port" =~ ^[0-9]+$ && "$candidate_port" =~ ^[0-9]+$ && "$base" =~ ^/([a-zA-Z0-9_-]+/)*$ && "$port" != "$candidate_port" ]] || exit 1
[[ -d "$root" && -f "$root/.pulse-deployment" ]] || { echo 'Uninitialized project directory' >&2; exit 1; }
exec 9>"$root/.deploy.lock"
flock -n 9 || { echo 'Deployment already in progress' >&2; exit 1; }
release="$root/releases/$release_id"
incoming="$root/incoming/$release_id"
[[ -d "$incoming/dist/client" && -f "$incoming/dist/server/index.js" && ! -e "$release" ]] || exit 1
[[ "$(cat "$incoming/REVISION")" == "${release_id#*-}" ]] || exit 1
[[ "$(cat "$incoming/BASE_PATH")" == "$base" ]] || { echo 'Artifact base path mismatch' >&2; exit 1; }
env_file="/etc/$service.env"
[[ -r "$env_file" ]] || { echo 'Environment file is not readable by deploy account' >&2; exit 1; }
previous=''
if [[ -L "$root/current" ]]; then
 previous=$(readlink -f "$root/current")
 [[ "$previous" == "$root/releases/"* && -f "$previous/.known-good" ]] || { echo 'Current release is not recorded known-good' >&2; exit 1; }
 # Confirm that the recorded release still serves before changing anything.
 curl --fail --silent --show-error --max-time 5 "http://127.0.0.1:$port${base}health" >/dev/null
elif [[ -e "$root/current" ]]; then
 echo 'Refusing to replace a legacy direct-path deployment' >&2; exit 1
fi
mkdir -p "$root/releases"
mv "$incoming" "$release"
cd "$release"
# Schema migrations must remain additive/backward-compatible with the previous
# release. Stop for a separate, approved migration for destructive changes.
/usr/bin/node --env-file="$env_file" dist/server/cli.js migrate
[[ -z "$(ss -H -ltn "sport = :$candidate_port")" ]] || { echo 'Candidate port already in use' >&2; exit 1; }
candidate_pid=''
cleanup(){ if [[ -n "$candidate_pid" ]]; then kill "$candidate_pid" 2>/dev/null || true; wait "$candidate_pid" 2>/dev/null || true; fi; }
trap cleanup EXIT
HOST=127.0.0.1 PORT="$candidate_port" APP_BASE_PATH="$base" WORKER_ENABLED=false NODE_ENV=production /usr/bin/node --env-file="$env_file" dist/server/index.js >"$release/preflight.log" 2>&1 &
candidate_pid=$!
healthy=false
for ((i=0;i<20;i++)); do
 kill -0 "$candidate_pid" 2>/dev/null || break
 if curl --fail --silent --max-time 2 "http://127.0.0.1:$candidate_port${base}health" >/dev/null; then healthy=true; break; fi
 sleep 1
done
[[ "$healthy" == true ]] || { echo 'Candidate health check failed; see preflight.log' >&2; exit 1; }
cleanup; candidate_pid=''
switch_to(){ ln -s "$1" "$root/.current-next"; mv -Tf "$root/.current-next" "$root/current"; }
[[ ! -e "$root/.current-next" && ! -L "$root/.current-next" ]] || { echo 'Stale switch link needs inspection' >&2; exit 1; }
switch_to "$release"
verify_live(){ for ((i=0;i<20;i++)); do if curl --fail --silent --max-time 2 "http://127.0.0.1:$port${base}health" >/dev/null; then return 0; fi; sleep 1; done; return 1; }
if ! sudo -n systemctl restart "$service.service" || ! verify_live; then
 echo 'Release failed; restoring recorded known-good release' >&2
 if [[ -n "$previous" ]]; then
  switch_to "$previous"
  sudo -n systemctl restart "$service.service"
  verify_live || { echo 'Rollback health check failed; operator intervention required' >&2; exit 1; }
 else
  sudo -n systemctl stop "$service.service"
 fi
 exit 1
fi
touch "$release/.known-good"
# Only remove old directories generated by this release protocol, never data.
for old in "$root"/releases/*; do
 [[ -d "$old" && ! -L "$old" ]] || continue
 [[ "$(basename "$old")" =~ ^[0-9]+-[0-9a-f]{40}$ ]] || continue
 [[ "$old" == "$release" || "$old" == "$previous" ]] && continue
 [[ -f "$old/.known-good" ]] || continue # retain failed diagnostics for operator review
 rm -rf -- "$old"
done
echo "Released $release_id; previous known-good retained: ${previous:-none}"
